-- MySQL Script generated by MySQL Workbench
-- tis 28 nov 2023 18:24:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema uno
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema uno
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uno` ;
USE `uno` ;

-- -----------------------------------------------------
-- Table `uno`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uno`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `registered` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uno`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uno`.`games` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `winner` INT NOT NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `winner_idx` (`winner` ASC) VISIBLE,
  CONSTRAINT `winner`
    FOREIGN KEY (`winner`)
    REFERENCES `uno`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
