services:
  app:
    build:
      dockerfile: ./docker/Dockerfile-app
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      - CARGO_TARGET_DIR=/target
    volumes:
      - .:/app

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: uno
      MYSQL_USER: uno_user
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33006:3306

  adminer:
      image: adminer
      restart: always
      ports:
        - 9000:8080

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8080:80


volumes:
  db_data: