FROM rust

ARG USER_ID
ARG GROUP_ID

RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
    userdel -f www-data &&\
    if getent group www-data ; then groupdel www-data; fi &&\
    groupadd -g ${GROUP_ID} www-data &&\
    useradd -l -u ${USER_ID} -g www-data www-data &&\
    install -d -m 0755 -o www-data -g www-data /home/www-data; fi

WORKDIR /app
COPY ./.env .
COPY migrations .

RUN apt update && apt install -y libpq-dev libsqlite3-dev libmariadb-dev

RUN chown -R www-data:www-data /app \
    && mkdir /target \
    && chown -R www-data:www-data /target

USER www-data

RUN cargo install cargo-watch && cargo install diesel_cli --features mysql

CMD ["cargo", "watch", "-x", "run"]
